### ISSUE TITLE
Fatal error: max-retries exceeded

### ISSUE THREAD

**Issue by puzich** [christophschlosser/drone-ftps#21]
Currently, I get the error "Fatal error: max-retries exceeded" if I try to upload files to the server. And that on two different projects. I can't explain it to myself. On server side, there is a 200-message, so normally the file was successfully transferred. Do you have any idea?

**Comment by cschlosser** [comment]
No sorry unfortunately not.
Maybe you can find help here: https://github.com/lavv17/lftp/issues

**Comment by puzich** [comment]
I've took your code and created the docker image again with may again. Now it works. Seems that it is an error at docker side.

**Comment by cschlosser** [comment]
Thanks for investigating this!
I will trigger a rebuild of the image
