### ISSUE TITLE
secure upload for FTP servers with broken configs

### ISSUE THREAD

**Issue by servusoft** [christophschlosser/drone-ftps#3]
@christophschlosser: I create a new issue, becuause the previous topic was bad

I found a solution to use SSL with broken configs, if e.g. CN of the cereficats not matchs to hostname.
the error like `Certificate verification: subjectAltName does not match ‘domian.tld’ ` may be supressed.

its occure often, if the provider use a widcard sertficate, and/or if isn't possible the FTP server to configure. a self signed cert has the same behavior.

its possible with the splitting of the SSL params to  `secure` and `verify`. look at: 
https://github.com/servusoft/drone-ftps/commit/1e86957f100fc0f5edaf9785079cf4946c89e9d3

more sense makes a import of certs or a fingerprint of certs, but its a little complicated.

with a additional parameter `--verbose` its get feedback about transfered files. 

I can make a PR, if its Ok.

**Comment by cschlosser** [comment]
Feel free to do so

**Comment by servusoft** [comment]
done. now with docu: https://github.com/christophschlosser/drone-ftps/pull/4
