### ISSUE TITLE
Error message "chmod" after file transferred

### ISSUE THREAD

**Issue by squaresun** [christophschlosser/drone-ftps#7]
There is an error message after transferred files if ftp user don't have such permissions.

```chmod: Access failed: 550 Could not change perms on f03d9f5a912b76ec4a42d1b69a44aa8e.png```

I think it comes from [mirror](https://github.com/christophschlosser/drone-ftps/blob/c1d69b7ccb9c6a17a9b57d0da47d1fd94f61079a/upload.sh#L47), which don't have ```-p``` in this line.

I added a parameter for specifying whether ```-p``` is needed

**Comment by cschlosser** [comment]
Should be fixed
